services:
  app:
    image: communication_app:v1
    build:
      context: .
      dockerfile: Dockerfile
    container_name: communication_app
    command: ["./communication_interface"]
    environment:
    - COMM_INTERFACE_KEY=00112233445566778899AABBCCDDEEFF
    networks:
      - communication_net

  tests:
    image: communication_app:v1
    build:
      context: .
      dockerfile: Dockerfile
    container_name: communication_tests
    command: ["./runTests"]
    depends_on:
      - app
    networks:
      - communication_net

networks:
  communication_net:
    driver: bridge
